# Powerlifting Project
This is an ongoing project on finding if there are any parts of powerlfiting that have corrolation of lack there of that are thought to be there<br>
The first thing that i am going to do are import the libaries that i will be using so that i can better teach myself the intricacies of each of the libaries

This is one of many different powerlifting data sets that i am going to be looking into going from regional lifters, to nations and then world stage lifts.
This data set is of the worlds. 
The data that i am going to be using for this project is from the website openpowerlifting.org and this will be the same with all my datasets

Data from 2020 is unavailable as of the pandemic so most meets were cancelled for this period

The Aim of this project is to see if there are any variances or corrolation in data points that have never been seen before, This is a personal project so that i can <br>
better adapt my own training. But also hopefully once it is done it will be able to help other lifters. 

The Columns that are in this Data set are as follows:<br>
- Rank - This is the posiiton in which the lifter finished <br>
- Lifter - This is the name of the lifter<br>
- Sex - Gender of the lifter<br>
- Age - Age of the lifter in years<br>
- Equip - Type of equipment uses<br>
- Class - Weight class<br>
- Weight - Actual weight when weighed in before the event<br>
- Squat - Best squat on the day in (kg)<br>
- Bench - Best Bench on the day in kg<br>
- Deadlift - Best Deadlift on the day in kg<br>
- Total - best 3 lifts added together in kg<br>
- GLP - Total lifts in relation

Luckily for this project openpowerlifting have provided the entire dataset for all of their data so that i can easily access it all and use the relevant aspects for my analysis.

In [23]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
dataset = pd.read_csv('powerlifting.csv')

#Data has now been imported into my notebook for further analysis

C:\Users\Pete\AppData\Local\Temp\ipykernel_20028\2020860755.py:4: DtypeWarning: Columns (33,35,38) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('powerlifting.csv')

In [24]:
print(dataset.shape)
print(dataset.columns)
print(dataset.memory_usage(deep=True).sum())
#We can see that this dataset has 2.8million rows and 41 columns with a size of 3674948072 whihc i will try and trim to give us a more efficient looking dataset.

(2838796, 41)
Index(['Name', 'Sex', 'Event', 'Equipment', 'Age', 'AgeClass',
       'BirthYearClass', 'Division', 'BodyweightKg', 'WeightClassKg',
       'Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Squat4Kg', 'Best3SquatKg',
       'Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Bench4Kg', 'Best3BenchKg',
       'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Deadlift4Kg',
       'Best3DeadliftKg', 'TotalKg', 'Place', 'Dots', 'Wilks', 'Glossbrenner',
       'Goodlift', 'Tested', 'Country', 'State', 'Federation',
       'ParentFederation', 'Date', 'MeetCountry', 'MeetState', 'MeetTown',
       'MeetName'],
      dtype='object')
3674948072

In [25]:
dataset.head(10)
#This gives us a good understadnding of how the data is laid out so that we can clean the data more accuratly, I will now beging by removing the columns i do not require

,Name,Sex,Event,Equipment,Age,AgeClass,BirthYearClass,Division,BodyweightKg,WeightClassKg,...,Tested,Country,State,Federation,ParentFederation,Date,MeetCountry,MeetState,MeetTown,MeetName
0,Alona Vladi,F,SBD,Raw,33.0,24-34,24-39,O,58.30,60,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
1,Galina Solovyanova,F,SBD,Raw,43.0,40-44,40-49,M1,73.10,75,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
2,Daniil Voronin,M,SBD,Raw,15.5,16-17,14-18,T,67.40,75,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
3,Aleksey Krasov,M,SBD,Raw,35.0,35-39,24-39,O,66.65,75,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
4,Margarita Pleschenkova,M,SBD,Raw,26.5,24-34,24-39,O,72.45,75,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
5,Sergey Timoshenko,M,SBD,Raw,15.5,16-17,14-18,T,78.80,85,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
6,Vladimir Karavaev,M,SBD,Raw,57.5,55-59,50-59,M2,79.65,85,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
7,Tatyana Altunina,F,SBD,Raw,26.0,24-34,24-39,O,96.50,105,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
8,Ruslan Gasanov,M,SBD,Raw,31.5,24-34,24-39,O,102.55,105,...,NaN,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament
9,Ekaterina Glukhova,F,SBD,Wraps,25.5,24-34,24-39,O,54.80,55,...,Yes,Russia,NaN,GFP,NaN,2019-05-11,Russia,NaN,Bryansk,Open Tournament

In [26]:
dataset.value_counts('Event')
#checking to see what sort of data is in this field as inofmration seems ambigious, as a result find the data is not needed so will be dropping.

Event
SBD    1952496
B       645073
D       164646
BD       56635
S        15175
SB        2927
SD        1844
dtype: int64

In [27]:
dataset.drop(['MeetTown', 'MeetName','State','Glossbrenner','BirthYearClass','ParentFederation','MeetState','Event'], axis=1, inplace=True)
#Now that i have dropping the initial columns that i know have no use for any of my needs i can further delve into the data and see what bits to abstract and clean so that i have the most relevent data

In [28]:
dataset.info()
#I used the info method so to better understadn the datatypes in my columns and it is also a very nice way of indexing my columns so that i can save time writing the names out each time i was do do a quick search

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2838796 entries, 0 to 2838795
Data columns (total 33 columns):
 #   Column           Dtype
---  ------           -----
 0   Name             object
 1   Sex              object
 2   Equipment        object
 3   Age              float64
 4   AgeClass         object
 5   Division         object
 6   BodyweightKg     float64
 7   WeightClassKg    object
 8   Squat1Kg         float64
 9   Squat2Kg         float64
 10  Squat3Kg         float64
 11  Squat4Kg         float64
 12  Best3SquatKg     float64
 13  Bench1Kg         float64
 14  Bench2Kg         float64
 15  Bench3Kg         float64
 16  Bench4Kg         float64
 17  Best3BenchKg     float64
 18  Deadlift1Kg      float64
 19  Deadlift2Kg      float64
 20  Deadlift3Kg      float64
 21  Deadlift4Kg      float64
 22  Best3DeadliftKg  float64
 23  TotalKg          float64
 24  Place            object
 25  Dots             float64
 26  Wilks            float64
 27  Goodlift         float64
 28  Tested           object
 29  Country          object
 30  Federation       object
 31  Date             object
 32  MeetCountry      object
dtypes: float64(21), object(12)
memory usage: 714.7+ MB

In [29]:
print(dataset.iloc[:10,[0,11,16,21,22,27]])
dataset.drop('Goodlift',axis=1,inplace=True)
#I am looking to make sure that this information is inline with what i am expecting along with seeing what the Goodlift columns is.
#After viewing i realised that this column is not nessary for any of my data analysis so it has been dropped

                     Name  Squat4Kg  Bench4Kg  Deadlift4Kg  Best3DeadliftKg  \
0             Alona Vladi       NaN       NaN          NaN            107.5
1      Galina Solovyanova       NaN       NaN          NaN            110.0
2          Daniil Voronin       NaN       NaN          NaN            105.0
3          Aleksey Krasov       NaN       NaN          NaN            170.0
4  Margarita Pleschenkova       NaN       NaN          NaN            125.0
5       Sergey Timoshenko       NaN       NaN          NaN            115.0
6       Vladimir Karavaev       NaN       NaN          NaN             55.0
7        Tatyana Altunina       NaN       NaN          NaN            140.0
8          Ruslan Gasanov       NaN       NaN          NaN            260.0
9      Ekaterina Glukhova       NaN       NaN          NaN             95.0

   Goodlift
0     57.10
1     56.76
2     41.24
3     66.68
4     39.34
5     39.09
6     47.35
7     51.79
8     81.45
9     51.38

In [30]:
dataset.isna().sum()
#This is able to show us alot of good information about our dataset. 
#With my analysis alot of the tests are going to be done using information relating to age, weight and their representative lifts
#This being said, if Bodyweight is a null value then this is data i am not interested in and will be removed from my data set, which is 36800 rows that will be removed
#Further due to the size of the null values i have decided to now only use the best Squat, best Bench and best Deadlift columns from the columns which represent the different lifts thats have been made,

Name                     0
Sex                      0
Equipment                0
Age                1047721
AgeClass            795102
Division              1429
BodyweightKg         36800
WeightClassKg        36098
Squat1Kg           2076867
Squat2Kg           2085272
Squat3Kg           2106570
Squat4Kg           2831047
Best3SquatKg        957618
Bench1Kg           1618456
Bench2Kg           1632992
Bench3Kg           1671525
Bench4Kg           2818961
Best3BenchKg        339294
Deadlift1Kg        1971985
Deadlift2Kg        1988081
Deadlift3Kg        2025128
Deadlift4Kg        2817957
Best3DeadliftKg     800598
TotalKg             194035
Place                    0
Dots                218326
Wilks               218326
Tested              747017
Country            1239177
Federation               0
Date                     0
MeetCountry              0
dtype: int64

In [31]:
power = dataset.copy()
#I have left a copy of this current dataset incase i want to go back and analysis the null values. But for this analysis i am now going to
#remove the columsn that i previously states, along with null values in Bodyweight
dataset.drop(['Country','Squat1Kg','Squat2Kg','Squat3Kg','Squat4Kg','Bench1Kg','Bench2Kg','Bench3Kg','Bench4Kg','Deadlift1Kg','Deadlift2Kg','Deadlift3Kg','Deadlift4Kg'], axis=1,inplace=True)

In [35]:
dataset = dataset.dropna(subset=['BodyweightKg','WeightClassKg','TotalKg','AgeClass'])
print(dataset.isna().sum())
print(dataset.shape)

Name                    0
Sex                     0
Equipment               0
Age                935404
AgeClass           705404
Division             1262
BodyweightKg            0
WeightClassKg           0
Best3SquatKg       812782
Best3BenchKg       180578
Best3DeadliftKg    618791
TotalKg                 0
Place                   0
Dots                    0
Wilks                   0
Tested             681894
Federation              0
Date                    0
MeetCountry             0
dtype: int64
(2602689, 19)

In [36]:
#Now i am going to rename some of the columns so that they are in line with camel case as is the norm in python 
dataset = dataset.rename(columns= lambda col_name : col_name.lower())
dataset = dataset.rename(columns={'ageclass':'age_class','bodyweightkg':'bodyweight_kg','weightclasskg':'weight_class_kg', 'best3squatkg':'best_squat', 
                                  'best3benchkg':'best_bench','best3deadliftkg':'best_deadlift','totalkg':'total_kg','meetcountry':'country'})

In [37]:
dataset.columns
#As you can now see all of our columns are now using the same camelcase format that is the industry standard when working with data in python.

Index(['name', 'sex', 'equipment', 'age', 'age_class', 'division',
       'bodyweight_kg', 'weight_class_kg', 'best_squat', 'best_bench',
       'best_deadlift', 'total_kg', 'place', 'dots', 'wilks', 'tested',
       'federation', 'date', 'country'],
      dtype='object')

In [38]:
dataset.head()

,name,sex,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best_squat,best_bench,best_deadlift,total_kg,place,dots,wilks,tested,federation,date,country
0,Alona Vladi,F,Raw,33.0,24-34,O,58.30,60,80.0,60.0,107.5,247.5,1,279.44,282.18,Yes,GFP,2019-05-11,Russia
1,Galina Solovyanova,F,Raw,43.0,40-44,M1,73.10,75,105.0,67.5,110.0,282.5,1,278.95,272.99,Yes,GFP,2019-05-11,Russia
2,Daniil Voronin,M,Raw,15.5,16-17,T,67.40,75,100.0,62.5,105.0,267.5,1,206.40,206.49,Yes,GFP,2019-05-11,Russia
3,Aleksey Krasov,M,Raw,35.0,35-39,O,66.65,75,137.5,122.5,170.0,430.0,1,334.49,334.94,Yes,GFP,2019-05-11,Russia
4,Margarita Pleschenkova,M,Raw,26.5,24-34,O,72.45,75,90.0,50.0,125.0,265.0,1,194.46,193.55,Yes,GFP,2019-05-11,Russia